jupyter-naas/awesome-notebooks

_Workflows/_Send_emails_from_gsheets.ipynb
Add first workflow example in awesome notebooks
=> feat: add workflow

README.md
Add a single World Health Indicator based on COVID-19 Daily Active Cases
=> Add COVID-19 Active Cases Notebook

IUCN/IUCN_Extinct_species.ipynb, README.md, generate_readme.ipynb
Pull request from the datamining course with @jravenel about threatened species. Can you please review it ? Thanks !
=> 1st commit on IUCN

.gitignore, Hugging Face/Hugging_Face_Summarization_using_NLP.ipynb, Summarization/Summarization_NLP_demo.ipynb
=> feat: Summarization NLP using Naas_drivers

NLP/Naas_nlp_qna.ipynb
Template for QNA in the NLP folder
=> feat: NLP QNA demo

Reddit/Reddit_Get_Hot_Posts_From_Subreddit.ipynb, Telegram/Telegram_Create_crypto_sentiment_bot.ipynb
Hello @jravenel, 
This is the first notebook demonstrating getting hot posts data from a subreddit in Reddit.  
closes #160
=> Reddit - Get hot posts from Subreddit/Community

AWS/AWS_Daily_biling_notification_to_slack.ipynb
This pull request is adding a notebook that can be used to get a daily notification about your AWS bill.
Example of message you will get:
> :wave: Daily AWS Billing notification
Current spending: [-42.00$]
Forecast: [42.00$]
End of month estimate: [-84.00$]
You can download the details here :point_down: https://public.naas.ai/...
💎 You will also be able to download a CSV file containing the details of the bill.
You can view the notebook [here](https://nbviewer.jupyter.org/github/jupyter-naas/awesome-notebooks/blob/aws-billing-notifications/AWS/AWS_Daily_biling_notification_to_slack.ipynb) or via the following screenshot:
=> feat: Aws daily billing notification to slack

README.md
Reverts jupyter-naas/awesome-notebooks#221
=> fix: Revert "Update README.md"

AWS/AWS_Get_files_from_S3_bucket.ipynb
Added AWS notebook to get file object and generate pre-signed url to share it with others.
=> aws-getfiles-presigned-url

Naas Auth/Naas_Auth_bearer_validate.ipynb, Naas Auth/Naas_Auth_connect.ipynb, Naas Auth/Naas_Auth_users_me.ipynb
This pull request is adding some notebooks to show how to use [auth.naas.ai](https://auth.naas.ai) 🎉
=> feat: Add naas-auth awesome notebooks

Remoteok/Remoteok_Post_daily_jobs_on_slack.ipynb
Hey @FlorentLvr !!
This is the pr related to this issue #368 
All changes are now done
Safe to push into production!
Thanks!
=> fix: post daily jobs bug

HubSpot/HubSpot_Delete_Task.ipynb, HubSpot/HubSpot_Get_Task.ipynb, HubSpot/HubSpot_Update_Task.ipynb
Patch function need to be reused from Hubspot -> HSCRUD class.
Added temporary to test the update logic
=> FT. Hubspot CRUD Operations

Twilio/Twilio_Send_SMS.ipynb
This is the Template to send messages to verified Phones using Twilio.
=> Twilio-Naas

Google Sheets/Google_Sheets_Send_data_to_MongoDB.ipynb, MongoDB/MongoDB_Send_data_to_Google_Sheets.ipynb
@OketunjiOludolapo, this is the new branch :)
Could you please check the 2 notebooks work on your side and send me a quick video of the process and the execution in slack (DM) ?
It could be awesome if you could detailed a bit more the Mongo setup. 
Thanks a lot :pray:
=> feat: sync gsheet mongo

Slack/Slack_Add_New_Slack_User_To_Google_Sheets.ipynb
Hey @Dr0p42!
Updated the notebook with the required code,
Do have a look,
Thanks!
=> 420 slack add new slack user to google sheets 

Notion/Notion_Send_Slack_Messages_For_New_Notion_Database_Items.ipynb
Referring to this issue #430 
Updated the notebook with the required code
Do have a look @Dr0p42!
Thanks!
=> 430 notion send slack messages for new notion database items 

GitHub/GitHub_Add_new_issues_as_page_in_Notion_database.ipynb, GitHub/GitHub_Add_new_member_to_team.ipynb, GitHub/GitHub_Get_pull_requests_from_repository.ipynb, GitHub/GitHub_Get_stargazers_from_repository.ipynb, GitHub/GitHub_Get_weekly_commits_from_repository.ipynb
Hey @FlorentLvr,
this is in reference to issue #958
Do have a look
Thanks!
=> GitHub add new member to team

.github/workflows/ensure_issue_is_linked.yaml
=> feat: Add a new workflow to check if an issue is linked to a PR

Notion/Notion_Add_new_github_member_to_team_from_database.ipynb
Referring to this issue #957 
Thanks!
=> feat: add github member from notion

Affinity/Affinity_Sync_with_Notion_database.ipynb
This new notebook can be used to sync an Affinity List with a Notion Database.
=> feat: Affinity sync with Notion database

README.md
Updated README by adding a link to the contributor's guide notion page.
[issue link](https://github.com/jupyter-naas/awesome-notebooks/issues/1028)
=> feat: added contributor's guide to readme

GitHub/GitHub_Get_issues_from_repo.ipynb
Referring to this issue #1066 , here is the updated notebook template
Thanks!
=> fix: template reformatted

Typeform/Typeform_Log_New_Typeform_Entries_In_Notion_Databases.ipynb
Referring to this issue #431,
here is the updated PR
Thanks!
=> 431 typeform log new typeform entries in notion databases

LinkedIn/LinkedIn_Get_age_and_gender_from_profile_picture.ipynb
This is done! 
Added image input checks and exception handling to make the classification pipeline more robust.
=> feat: input checks and exception handling

LinkedIn/LinkedIn_Send_invitations_to_post_commenters.ipynb, LinkedIn/LinkedIn_Send_message_to_new_connections.ipynb, LinkedIn/LinkedIn_send_invitations_to_post_commenters.ipynb
Hi Jeremy/Florent/Maxime,
This template automates the task of sending the introductory message to current day's new connections on LinkedIn, please review it and let me know if it is good to go ahead.
Thank you!
=> feat: linkedin send message to new connections #977

LinkedIn/LinkedIn_send_invitations_to_post_commenters.ipynb
Hi Jeremy,
This is done, request you to please review my PR and confirm if everything is fine.
=> feat: send invitations to all the commenters of a post on LinkedIn #973

Streamlit/Streamlit_Create_prediction_app.ipynb
fix import but still have problem at end of execution. 
Can you help @Dr0p42?
Thanks
n
=> fix: import lib

LinkedIn/LinkedIn_Send_followers_demographic_data_to_a_Google_Sheets_spreadsheet.ipynb, LinkedIn/LinkedIn_Send_followers_demographic_data_to_a_google_sheet.ipynb
This template allows the users to pull the below details regarding their LinkedIn followers to a google sheet:
1. Country of followers
2. Industries followers belong to
3. Companies followers are working at
=> feat: Send LinkedIn followers demographic data to a google sheet #1108

Pyvis/Pyvis_Create_a_network_visualization.ipynb
Added an example on how to build a network graph. 
Here is the issue: https://github.com/jupyter-naas/awesome-notebooks/issues/1125 :)
=> feat: added a new Pyvis folder + example

Dash/Dash_Deploy_app_in_Naas.ipynb
adding dash deployment example
=> feat: add dash folder and deploy example

AbstractAPI/Abstractapi-get-ip-geolocation.ipynb, AbstractAPI/Abstractapi_Get_IP_Geolocation.ipynb
This pull request resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1150
Here is an example of the performance that can be achieved on Naas with an Enterprise plan (default machine):
We can of course go higher with a more powerful instance by reaching out to us.
=> feat(Abstract-API): Add Abstractapi-get-ip-geolocation notebook

BigQuery/BigQuery_Create_table_from_csv.ipynb, BigQuery/BigQuery_Read_Table.ipynb, BigQuery/bigqueryconnector.py
Added a connector module for establishing a connection with BigQuery and templates for reading tables and creating tables using a CSV file.
This was inspired by the Snowflake templates available already.
@jravenel Let me know if this is useful and I can create a few other templates similar to what has already been done for Snowflake.
=> BigQuery Connector

Python/Python_Locate_Addresses.ipynb, Python/Python_Locate_Coordinates.ipynb
Hi @jravenel , could you please review these changes?
=> Python - Locate_addresses 

GitHub/GitHub_Create_repository_on_personal_account.ipynb, GitHub/Github_Create_Repo.ipynb
=> 1217-Create-Github-Repo

CSV/CSV_Read_file.ipynb, CSV/CSV_Save_file.ipynb
Added some comments for beginners like me who starts with csv files
=> adding minor comments

Text/Text_Reformat_Text_Without_Spaces.ipynb
I have added the template to reformat text that does contain any spaces.
A slight limitation that this template does have is the fact that it ignores any special characters that are contained in the text. I have addressed the exclusion of periods (.) as I thought this was the most important character to be included.
As given here, most of the solution that have already tackled this issue do not seem to address these special characters,
https://stackoverflow.com/questions/8870261/how-to-split-text-without-spaces-into-list-of-words
Further, as explained here, the process of adding correct punctuation to text also seems to be a little bit involved,
https://stackoverflow.com/questions/31514136/how-to-add-punctuation-to-text-using-python
As a result, I was hoping that we can handle the …
=> [PR] added the template to reformat text that does not contain any spaces

Python/Python_Rename_file.ipynb
Added the code snippet with naas template for renaming files.
Hey @FlorentLvr kindly review and approve the PR
=> Python - Rename file #1233

Python/Python_Find_Phone_Number_in_string.ipynb
> ### Why:
> Closes #1216 
> 
> ### What's being changed:
> added Python notebook to find phone number in a string
=> added python notebook to find phone number in a string

Python/Python_Copy_files_and_subdir_from_directory_to_another_directory.ipynb.ipynb, Python/Python_Create_dataframe_from_lists.ipynb, Tool/folder - action/file_actions.ipynb
Tags: #python #os #shutil #operations #snippet
**Author:** [Parth Panchal](https://www.linkedin.com/in/parthpanchal8401/)
=> Python - Copy files and subdir from directory to another directory

Twilio/Twilio_Make_Call.ipynb
Closes: #1224 
Worked on Twilio calling functionality.
=> Added: twilio-make-call

Python/Python_Convert_PNG_Images_To_JPG.ipynb
Added template Python to convert png images to jpg. #1201
Waiting for your review.
=> Added template Python_convert_png2jpg

Python/Python_Organize_Directories_based_on_file_types.ipynb
This PR closes #1213
I organized files based on data scientists' work as I assume that the user is mostly a data scientist. and I'm open to discussion.
=> Added template Python_Organize_Directories_based_on_files_extensions

GitHub/Github_Create_newsletter_based_on_repository_activity.ipynb
Modified the newsletter content as discussed in the Issue to send proper e-mail content.
=> Feat: Improve the generate newsletter template

Python/Python_Create_Strong_Random_Password.ipynb
=> feat:: create strong random password

README.md
Fixed the slack link preview in `README.md`
Fixes: #1336
=> Slack link preview

OpenBB/OpenBB_Create_an_OpenBB_kernel_on_Naas.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1341
A quick proof of the result
=> feat: Add OpenBB create kernel notebook

Naas/Naas_Create_Kernel.ipynb
This pull request resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1354
=> feat: Add template to make it easier to create new Kernels

Pandas/Pandas-Drop-Columns-By-Index.ipynb, Pandas/Pandas_Drop_Columns_By_Index.ipynb
This is a Pull request for #1310
=> 1310-pandas-drop-the-columns-by-index

Pandas/Pandas_Drop_Duplicate_Columns.ipynb
=> #1309- Pandas Drop Duplicate Columns

OpenAI/OpenAI_Generate_language_translations.ipynb
Added the notebook template to translate a given text to a language of choice.
Let me know if there are any suggestions for improvement.
=> OpenAI - Generate language translations

Azure Blob Storage/Azure_Blob_Storage_Upload_files.ipynb, Azure Blob Storage/azure_blob_storage_upload_files.ipynb
The following code snippet can be used to update a file into blob storage.
=> feat: Azure blob storage - upload files

Twitter/Twitter_Add_member_to_list.ipynb, Twitter/Twitter_Get_members_of list.ipynb
Hello @FlorentLvr @Dr0p42 @jravenel 
I have made the notebook kindly review it.
The issue is #1357 twitter add a member to list.
Thanks.
=> Notebook Commit

Twitter/Twitter_Remove_member_from_list.ipynb
Hello @FlorentLvr @Dr0p42 @jravenel
I have made the notebook kindly review it.
The issue is #1358  twitter add a member to list.
Thanks.
=> Commit 1 1358

.github/workflows/generate_readme.yaml
=> Fix: Generate README workflow

Agicap/Agicap_List_companies.ipynb, FEC/FEC_Visualiser_Bilan_Treemap.ipynb, Naas/Naas_Create_Kernel.ipynb, OpenBB/OpenBB_Create_an_OpenBB_kernel_on_Naas.ipynb, Panel/Panel_Create_a_Panel_kernel_on_Naas.ipynb, Plotly/Plotly_Create_Balance_Sheet_Treemaps.ipynb, Plotly/Plotly_Create_Treemaps_with_plotly.graph_objects.ipynb, SQLite/SQLite_Create_Database_file.ipynb, SQLite/SQLite_Create_Table_in_Database.ipynb, SQLite/SQLite_Insert_data_in_Table.ipynb, SQLite/SQLite_List_Tables_in_Database.ipynb, SQLite/SQLite_Read_data_in_Table.ipynb, Twitter/Twitter_Add_member_to_list.ipynb, Twitter/Twitter_Get_members_of list.ipynb, Twitter/Twitter_Remove_member_from_list.ipynb, update_notebook.ipynb
This pull requests resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1396
=> fix: Update all open in naas badges

OpenAI/OpenAI_Write_a_blog_post.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1483
=> OpenAI - Write a blog post

OpenAI/OpenAI_Write_a_social_media_post.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1485
=> OpenAI - Write a social media post

OpenAI/OpenAI_Write_a_press_release.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1487
=> OpenAI - Write a press release

OpenAI/OpenAI_Brainstorm_ideas.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1489
=> OpenAI - Brainstorm ideas

OpenAI/OpenAI_Write_an_outline.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1491
=> OpenAI - Write an outline

Python/Python_Get_last_file_modified_from_directy.ipynb
https://github.com/jupyter-naas/awesome-notebooks/issues/1468
=> Python - Get last file modified from directy

OpenAI/OpenAI_Write_a_job_description.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1493
=> OpenAI - Write a job description

GitHub/GitHub_Get_files_added_on_Pull_Request_Merged.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1495
=> feat: GitHub - Get files added on Pull Request Merged

Supabase/Supabase_Email_Auth.ipynb
=> Added: Supabase Email Authentication

ZeroBounce/ZeroBounce_Validate_Single_Email.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1518
=> feat: ZeroBounce - Validate Single Email

Python/Python_Create_Email_Combination_with_Firstname_Lastname_Domain_address.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1520
=> feat: Python - Create Email Combination with Firstname, Lastname, Domain address

Bitly/Bitly_Delete_a_Bitlink.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1501
=> feat: Bitly - Delete a Bitlink

Bitly/Bitly_Update_a_Bitlink.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1503
=> feat: Bitly - Update a Bitlink

Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_Referrers.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1512
=> feat: Bitly - Get Metrics for a Bitlink by Referrers

Bitly/Bitly_Get_a_Clicks_Summary_for_a_Bitlink.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1472
=> Bitly - Get a Clicks Summary for a Bitlink

Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_Country.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1475
=> Bitly - Get Metrics for a Bitlink by Country

Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_Device_Type.ipynb, Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_Devices.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1510
=> feat: Bitly - Get Metrics for a Bitlink by Device Type

Bitly/Bitly_Get_Clicks_for_a_Bitlink.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1508
=> feat: Bitly - Get Clicks for a Bitlink

Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_City.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1506
=> feat: Bitly - Get Metrics for a Bitlink by City

OpenAI/OpenAI_Generate_Text_to_Speech.ipynb
- Fixes: #1376 
- Made use of the Google Text to Speech API to generate the audio output of the OpenAI prompt response.
=> OpenAI - Generate Text-to-Speech

Pandas/Pandas_Filter_DataFrame.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1525
=> feat: Pandas - Filter DataFrame

gTTS/gTTS_Save_Text_to_Speech_to_MP3.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1523
=> feat: gTTS - Save Text to Speech to MP3

GitHub/GitHub_List_organization_repositories.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1536
=> feat: GitHub - List organization repositories

GitHub/GitHub_Get_a_repository.ipynb, GitHub/GitHub_List_organization_repositories.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1538
=> feat: GitHub - Get a repository

Creditsafe/Creditsafe_Get_Company_Credit_Report.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1546
=> feat: Creditsafe - Get Company Credit Report

Python/Python_Read_json_file.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1556
=> feat: Python - Read json file

Python/Python_Save_json_file.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1558
=> feat: Python - Save json file

Python/Python_Pickle_save_object.ipynb, Python/Python_Save_dict_to_pickle.ipynb
Hello @FlorentLvr @jravenel @Dr0p42 @srini047 
Could you review the notebook ?
Thank you
=> Pickle save JSON

GitHub/GitHub_Get_files_added_on_pull_request.ipynb, GitHub/GitHub_Get_files_changed_on_pull_request.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1550
=> feat: GitHub - Get files changed on pull request

Twilio/Twilio_Add_SMS_to_Google_Sheets_spreadsheet.ipynb, Twilio/Twilio_Send_SMS_add_new_rows_in_Google_Sheets.ipynb
Fixes: #921 
Screen recording: https://www.loom.com/share/de98da464c3842e98edee6668ce30cea
=> Added: Twilio SMS text messages Google Sheets as new rows

Python/Python_Read_pickle_file.ipynb
Hello @FlorentLvr @jravenel @Dr0p42 @srini047 
Can you review this pull request ?
Thanks
=> Read pickle file commit

Naas/Naas_Add_Scheduler.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1569
=> feat: Naas - Add Scheduler

Naas/Naas_Delete_Scheduler.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1571
=> feat: Naas - Delete Scheduler

LinkedIn/LinkedIn_Create_Post.ipynb, LinkedIn/LinkedIn_Create_Post_with_Image.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1497
=> feat: LinkedIn - Create Post

Naas/Naas_Add_Asset.ipynb, Naas/Naas_Add_and_Delete_Asset.ipynb, Naas/Naas_Delete_Asset.ipynb, Naas/Naas_List_Assets.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1580
=> feat: Naas - Add and Delete Asset

OpenAI/OpenAI_Generate_Dialogue.ipynb
Fixes: #1369 
[Demo](https://youtu.be/qQuymF9MiVM)
=> OpenAI - Generate Dialogue

Plotly/Plotly_Create_Bubblemap_by_City.ipynb, Plotly/Plotly_Display_Values_by_City_in_Worldmap.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1554
=> feat: Plotly - Display Values by City in Worldmap

Excel/Excel_List_sheets.ipynb, Excel/Excel_List_sheets_in_workbook.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1612
=> feat: Excel - List sheets

GitHub/GitHub_Download_Excel_file_from_URL.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1614
=> feat: GitHub - Download Excel file from URL

Python/Python_Convert_URL_to_string.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1623
=> feat: Python - Convert URL to string

Pandas/Pandas_Flatten_MultiIndex_Columns.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1625
=> feat: Pandas - Flatten MultiIndex Columns

Python/Python_Clean_your_download_folder.ipynb
fixex: #1606 
Recording: https://youtu.be/g19d8KuDG5c
=> feat: clean your folder

Python/Python_Flatten_nested_dict.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1633
=> feat: Python - Flatten nested dict

Clockify/Clockify_Get_all_my_workspaces.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1637
=> feat: Clockify - Get all my workspaces

Boursorama/Boursorama_Get_EURIBOR_3_MOIS.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1635
=> feat: Boursorama - Get EURIBOR 3 MOIS

FED/FED_Visualize_Inflation_Rate.ipynb
fixes: #1338
Recording: https://youtu.be/oXbRNfHeCDE
=> feat: visualise the inflation rate

Polars/Polars_Read_CSV.ipynb, Polars/Polars_Read_dataframe.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1542
=> feat: Polars - Read dataframe

Google Calendar/Google_Calendar_List_events_from_calendar.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1600
=> feat: Google Calendar - List events from calendar

Naas/Naas_Start_data_product.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1659
=> feat: Naas - Start data product

Notion/Notion_Update_database_with_GitHub_repositories_info.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1662
=> feat: Notion - Update database with GitHub repositories info

GitHub/GitHub_List_team_members.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1671
=> feat: GitHub - List team members

Google Slides/Google_Slides_Create_a_blank_presentation.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1687
=> feat: Google Slides - Create a blank presentation

Google Slides/Google_Slides_Create_a_Slide.ipynb, Google Slides/Google_Slides_Create_a_blank_presentation.ipynb, Google Slides/Google_Slides_List_slides_in_presentation.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1698
=> feat: Google Slides - List slides in presentation

Google Slides/Google_Slides_Create_a_Slide.ipynb, Google Slides/Google_Slides_Duplicate_slide.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1700
=> feat: Google Slides - Duplicate slide

Notion/Notion_Update_page_relation.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1702
=> feat: Notion - Update page relation

Notion/Notion_Update_page_relation.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1702
=> feat: update variables

Naas/Naas_Add_Webhook.ipynb, Naas/Naas_Delete_Webhook.ipynb, Naas/Naas_List_Webhooks.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1683
=> feat: Naas - Add Webhook

Google Slides/Google_Slides_Replace_text_within_a_shape.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1695
=> feat: Google Slides - Replace text within a shape

Jupyter Notebooks/Jupyter_Notebooks_Apply_black_on_notebook_file.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1707
=> feat: Jupyter Notebooks - Apply black on notebook file

GitHub/GitHub_Get_team_membership_for_a_user.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1673
=> feat: GitHub - Get team membership for a user

GitHub/GitHub_Add_or_update_team_membership_for_a_user.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1675
=> feat: GitHub - Add or update team membership for a user

Python/Python_Delete_entire_directory_tree.ipynb, Python/Python_Remove_folder.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1709
=> feat: Python - Remove folder

GitHub/GitHub_Remove_team_membership_for_a_user.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1685
=> feat: GitHub - Remove team membership for a user

Stripe/Stripe_List_all_customers.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1715
=> feat: Stripe - List all customers

Agicap/Agicap_Export_treasury_plan.ipynb, Agicap/Agicap_Export_treasury_plan_by_account.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1713
=> feat: Agicap - Export treasury plan

Naas/Naas_Add_Secret.ipynb, Naas/Naas_Add_secret.ipynb, Naas/Naas_Delete_Secret.ipynb, Naas/Naas_List_Secrets.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1722
=> feat: Naas - Add secret

Notion/Notion_Add_bulleted_list_in_page.ipynb, Notion/Notion_Add_code_block_in_page.ipynb, Notion/Notion_Add_equation_in_page.ipynb, Notion/Notion_Add_heading_in_page.ipynb, Notion/Notion_Add_list_in_page.ipynb, Notion/Notion_Add_numbered_list_in_page.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1729
=> feat: Notion - Add list in page

BeautifulSoup/BeautifulSoup_List_social_network_links_from_website.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1733
=> feat: BeautifulSoup - List social network links from website

Naas/Naas_Find_Asset_link_from_path.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1735
=> feat: Naas - Find Asset link from path

Python/Python_Download_ZIP_from_URL.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1657
=> feat: Python - Download ZIP from URL

Python/Python_Get_next_occurrences_of_a_cron_job.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1737
=> feat: Python - Get next occurrences of a cron job

Pandas/Pandas_Transform_DataFrame_to_json_file.ipynb, Pandas/Pandas_Transform_Dataframe_to_dict.ipynb, Python/Python_Save_json_file.ipynb, Python/Python_Transform_DataFrame_to_json_file.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1739
=> feat: Python - Transform DataFrame to json file

Python/Python_Access_environment_variable.ipynb, Python/Python_Add_new_environment_variable.ipynb, Python/Python_Get_access_of_environment_variables.ipynb, Python/Python_Set_variables_in_environment.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1741
=> feat: Python - Set variables in environment

GitHub/GitHub_Clone_repository.ipynb, GitHub/GitHub_Clone_repository_and_switch_branch.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1743
=> feat: GitHub - Clone repository and switch branch

HubSpot/HubSpot_Get_all_pipelines_and_dealstages.ipynb, HubSpot/HubSpot_Send_sales_pipeline_to_Notion.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1711
=> feat: HubSpot - Send sales pipeline to Notion

Gmail/Gmail_Send_email.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1753
=> feat: Gmail - Send email

Clockify/Clockify_Remove_user_from_workspace.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1641
=> feat: Clockify - Remove user from workspace

Clockify/Clockify_Find_all_users_on_workspace.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1758
=> feat: Clockify - Find all users on workspace

Clockify/Clockify_Find_tasks_on_project.ipynb, Clockify/Clockify_Get_all_projects_on_workspace.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1764
=> feat: Clockify - Find tasks on project

Clockify/Clockify_Add_a_new_client.ipynb, Clockify/Clockify_Delete_client.ipynb, Clockify/Clockify_Get_client_by_ID.ipynb, Clockify/Clockify_Update_client.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1762
=> feat: Clockify - CRUD client

Clockify/Clockify_Get_time_entries_for_a_user_on_workspace.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1768
=> feat: Clockify - Get time entries for a user on workspace

Gmail/Gmail_Automate_response_from_keywords_in_mailbox.ipynb, Gmail/Gmail_Create_GitHub_issue_on_specific_email.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1776
=> feat: Gmail - Create GitHub issue on specific email

Gmail/Gmail_Create_draft_email.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1766
=> feat: Gmail - Create draft email

Python/Python_Calculate_relative_time_delta_between_two_dates.ipynb, Python/Python_Calculate_time_delta_between_two_dates.ipynb, Python/Python_Convert_relative_time_delta_to_months.ipynb, Python/Python_Convert_time_delta_to_months.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1790
=> feat: Python - Calculate time delta between two dates

Python/Python_Compress_images.ipynb
=> feat: Compress images

Advertools/Advertools_Analyze_website_content_using_XML_sitemap.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1746
=> feat: Advertools - Analyze website content using XML sitemap

FEC/FEC_Visualiser_Charges_Horizontal_Barchart.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1793
=> feat: FEC - Visualiser Charges Horizontal Barchart

Dash/Dash_Create_conditional_formatting_of_an_HTML_element.ipynb, Dash/Dash_Create_conditional_formatting_on_HTML_element.ipynb, Dash/Dash_Create_conditional_formatting_on_number_value.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1798
=> feat: Dash - Create conditional formatting of an HTML element

FEC/FEC_Lecture_des_fichiers.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1800
=> feat: FEC - Lecture des fichiers

OpenAI/OpenAI_Generate_text_summaries.ipynb
=> feat: generate text summaries

GitHub/GitHub_Reopen_issue.ipynb, GitHub/GitHub_Update_an_issue.ipynb, GitHub/GitHub_Update_issue.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1810
=> feat: GitHub - Update an issue

OpenAI/OpenAI_Act_as_a_chef.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1817
=> feat: OpenAI - Act as a chef

Python/Python_List_specific_files_from_directory_and_subdirectories.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1823
=> feat: Python - List specific files from directory and subdirectories

OpenAI/OpenAI_Create_chat_completion.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1755
=> feat: OpenAI - Create chat completion

OpenAI/OpenAI_Create_Completion.ipynb, OpenAI/OpenAI_Create_chat_completion.ipynb, OpenAI/OpenAI_Create_chat_conversation_with_OpenAI.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1827
=> feat: OpenAI - Create chat conversation with OpenAI

Naas/Naas_List_Schedulers.ipynb, Naas/Naas_List_Schedulers_with_all_executions.ipynb, Naas/Naas_List_Schedulers_with_last_execution.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1831
=> feat: Naas - List Schedulers

LangChain/LangChain_Pandas_Dataframe_Agent.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1833
=> feat: LangChain - Pandas Dataframe Agent

Dash/Dash_Create_download_button.ipynb, Dash/Dash_Create_spinner_button.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1847
=> feat: Dash - Create download button

Dash/Dash_Add_a_customisable_sidebar.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1855
=> feat: Dash - Add a customisable sidebar

Pandas/Pandas_Concatenate_dataframes.ipynb, Pandas/Pandas_Create_dataframe_from_dict.ipynb
hey I'm done, can you take a look please?
=> feat: concatenate dataframes

Stable Diffusion/Stable_Diffusion_Generate_image_from_text.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1750
=> feat: Stable Diffusion - Generate image from text

Pandas/Pandas_Iterate_over_DataFrame_rows_as_namedtuples.ipynb
just did this one as well, not sure if this is good enough anyways can you go check it ?
thx
=> feat: Pandas - Iterate over DataFrame rows as namedtuples

Pandas/Pandas_Save_dataframe_to_Excel.ipynb
=> feat : Pandas - Save dataframe to Excel 

Python/Python_Split_string.ipynb
=> feat: Python split string

Python/Python_Remove_all_spaces_on_string.ipynb, Python/Python_Remove_space_on_string.ipynb
hey, here is another, i did 2 method in this template, hope you will like it
=> feat : Python remove space on string

OS/OS_List_entries_in_directory.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1894
=> feat: OS - List entries in directory

Python/Python_Find_differences_between_stings.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1907
=> feat: Python - Find differences between stings

Pandas/Pandas_Get_n_smallest.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1904
=> feat: Pandas - Get n smallest

Pandas/Pandas_Get_n_largest.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1902
=> feat: Pandas - Get n largest

Deepl/Deepl_Translated_string_to_txt.ipynb
hey, i finished this one , i'm proud of the result
=> feat: Deepl - Translate text to .txt

Algolia/Algolia_Add_or_Replace_all_attributes_in_existing_records.ipynb, Algolia/Algolia_Add_or_Replace_all_attributes_in_single_record.ipynb, Algolia/Algolia_Delete_multiples_objects.ipynb, Algolia/Algolia_Delete_single_object.ipynb, Algolia/Algolia_Get_all_records_from_an_index.ipynb, Algolia/Algolia_List indices.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1919
=> feat: Algolia - Get all records from an index

Request/Request_Basic_HTTP_GET_Request.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1881
=> feat: Request - Basic HTTP GET Request

Request/Request_Sending_POST_Requests_with_Data.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1883
=> feat: Request - Sending POST Requests with Data

Pandas/Pandas_Sort_values_by_multiples_columns.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1899
=> feat: Pandas - Sort values by multiples columns

OpenAI/OpenAI_Count_tokens_with_tiktoken.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1944
=> feat: OpenAI - Count tokens with tiktoken

Harvest/Harvest_List_all_clients.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1911
=> feat: Harvest - List all clients

Python/Python_Manage_exception_with_try_except.ipynb
i finally did this one ,i added else and finally bloc
=> feat: Python - Manage exception with try except

Python/Python_Create_Secure_Hash_Algorithm.ipynb, Python/Python_Transform_string_to_Secure_Hash_Algorithm.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1927
=> feat: Python - Create Secure Hash Algorithm

Python/Python_Get_random_word.ipynb
I dunno if this one is good because it need a database
=> feat: Python - Get a random word

Python/Python_Pseudonym_generator.ipynb
=> feat: Python - Pseudonym generator

Python/Python_Convert_units.ipynb, Python/Python_Unit_converter.ipynb
This one is a bit long, but it works well
=> feat: Python - Unit converter

Twilio/Twilio_Send_SMS_Google_Calendar_Events.ipynb
Fixes: #904 
[Demo](https://youtu.be/OTFttitlN3E)
=> Twilio: Send SMS for Google Calendar events

LangChain/LangChain_CSV_Agent.ipynb, LangChain/LangChain_Pandas_Dataframe_Agent.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1835
=> feat: LangChain - CSV Agent

Slack/Slack_Send_blocks_to_channel.ipynb, Slack/Slack_Send_message_to_channel.ipynb
it's almost the same as send a message from Slack, but it works well
=> feat: Slack - Send blocks to channel

Python/Python_Convert_length.ipynb, Python/Python_Convert_speed.ipynb, Python/Python_Convert_temperature.ipynb, Python/Python_Convert_time.ipynb, Python/Python_Convert_volume.ipynb, Python/Python_Convert_weight.ipynb
here is multiple convert template
=> feat: convert multiple units

Request/Request_Handling_Errors_and_Exceptions.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1885
=> feat: Request - Handling Errors and Exceptions

OWID/OWID_Visualize_Oil_Consumption_through_the_Years.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1877
=> feat: OWID - Add notebook to visualize oil consumption

Pandas/Pandas_Concatenate_dataframes.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1878
=> fix: tipo Pandas_Concatenate_dataframes.ipynb

LangChain/LangChain_JSON_Agent.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1839
=> feat: LangChain - JSON Agent

OS/OS_Get_folder_stats.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1991
=> feat: OS - Get folder stats

LangChain/LangChain_Gmail_Toolkit.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1837
=> feat: LangChain - Gmail Toolkit

Dash/Dash_Deploy_app_in_Naas.ipynb, OWID/OWID_Visualize_Oil_Consumption_through_the_Years.ipynb, OWID/OWID_Visualize_Population_of_Different_Age_Groups.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1963
=> feat: OWID - Visualize population structure over the years

Agicap/Agicap_Get_bank_account_from_company.ipynb, Agicap/Agicap_Get_banks_accounts_from_company.ipynb, Agicap/Agicap_List_companies.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2010
=> feat: Agicap - Get bank account from company

Trello/Trello_List_Boards.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1665
=> feat: Trello - List Boards

Agicap/Agicap_Export_categories_from_company.ipynb, Agicap/Agicap_Get_inflow_categories_from_company.ipynb, Agicap/Agicap_Get_outflow_categories_from_company.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2013
=> feat: Agicap - Export categories from company

GitHub/GitHub_Clone_repository_and_switch_branch.ipynb, Trello/Trello_Get_Cards_on_a_Board.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1973
=> feat: Trello - Get Cards on a Board

Trello/Trello_Get_Lists_on_a_Board.ipynb, Trello/Trello_retrieve_list_id.ipynb
hey so i did this one because it was hard to get list ID for another template so i had the idea to do this one as well
=> feat: Trello - Retrieve List ID

Trello/Trello_Create_Card.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1667
=> feat: Trello - Create Card

Azure Blob Storage/Azure_Blob_Storage_List_blobs.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1720
=> feat: Azure Blob Storage - List blobs

Azure Machine Learning/Azure_Machine_Learning_Univariate_Timeseries_Inference.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1726
=> feat: Azure Machine Learning - Univariate Timeseries Inference

Azure Machine Learning/Azure_Machine_Learning_Univariate_Timeseries_Inference.ipynb
- The API key that was exposed in the Azure ML template has been fixed.
=> Fix: api key expose issue

Advertools/Advertools_Crawl_a_website.ipynb
=> Resolves #1880

Pandas/Pandas_Format_URL_as_clickable_link_on_column.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2041
=> feat: Pandas - Format URL as clickable link on column

Polars/Polars_Concatenate_DataFrames.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2048
=> feat: Polars - Concatenate DataFrames

Python/Python_Check_if_string_is_number.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2050
=> feat: Python - Check if string is number

Python/Python_Convert_string_boolean_to_boolean.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2052
=> feat: Python - Convert string boolean to boolean

OWID/OWID_Visualize_life_expectancy_at_birth_for_both_sexes_through_out_the_years.ipynb
It closes https://github.com/jupyter-naas/awesome-notebooks/issues/2060.
=> feat: OWID-Life expectancy

JSON/JSON_Convert_Python_Objects_to_JSON.ipynb, JSON/JSON_Save_dataframe_to_JSON_file.ipynb, JSON/JSON_Send_to_Google_Sheets_spreadsheet.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2078
=> feat: JSON - Convert Python Objects to JSON

JSON/JSON_Pretty_Print_JSON_Data.ipynb, JSON/JSON_Pretty_print_JSON_data.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2080
=> feat: JSON - Pretty Print JSON Data

OWID/OWID_Visualize_GDP_per_capita_through_the_years.ipynb, OWID/OWID_Visualize_Oil_Consumption_through_the_Years.ipynb, OWID/OWID_Visualize_Population_of_Different_Age_Groups.ipynb, OWID/OWID_Visualize_economic_freedom_through_the_years.ipynb, OWID/OWID_Visualize_life_expectancy_at_birth_for_both_sexes_through_out_the_years.ipynb
This closes https://github.com/jupyter-naas/awesome-notebooks/issues/2076.
=> OWID: economic freedom data

Forecast/Forecast_List_all_people.ipynb
This notebook will list all people from the forecast API. Forecast is a service that connects to harvest and allows you to plan for allocations to harvest projects.
=> Forecast - List all people

HubSpot/HubSpot_Get_meetings_associated_to_contact.ipynb, HubSpot/HubSpot_List_meeting_properties.ipynb, HubSpot/HubSpot_Retrieve_meetings.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2117
=> feat: HubSpot - Manage meetings

Naas/Naas_Delete_Asset.ipynb, Naas/Naas_Delete_Scheduler.ipynb, Naas/Naas_Delete_all_assets.ipynb, Naas/Naas_Delete_all_schedulers.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2140
=> feat: Naas - Delete all schedulers

Python/Python_Remove_HTML_tags_from_text.ipynb, RegEx/RegEx_Remove_HTML_tags_from_text.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2175
=> feat: Python - Remove HTML tags from text

Python/Python_Calculate_the_percentage_of_similarity_between_two_strings.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2185
=> feat: Python - Calculate the percentage of similarity between two strings

Agicap/Agicap_Get_transactions_by_account.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2203
=> feat: Agicap - Get transactions by account

HubSpot/HubSpot_Chat_about_HubSpot_contact_activities.ipynb, HubSpot/HubSpot_Chat_about_a_contact.ipynb, HubSpot/HubSpot_Get_contact_brief.ipynb, HubSpot/HubSpot_Get_deal_brief.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2171
=> feat: HubSpot - Chat about HubSpot contact activities

HubSpot/HubSpot_Create_company.ipynb, HubSpot/HubSpot_Delete_company.ipynb, HubSpot/HubSpot_Get_company.ipynb, HubSpot/HubSpot_Update_company.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2179
=> feat: HubSpot - Create company

IPython/IPython_Display_dynamic_link_in_Jupyter_Lab.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2220
=> feat: IPython - Display dynamic link in Jupyter Lab

Matplotlib/Matplotlib_Create_Barchart.ipynb
=> typo fixed

OpenAI/OpenAI_Act_as_a_Customer.ipynb
This PR closes https://github.com/jupyter-naas/awesome-notebooks/issues/2285.
=> OpenAI - Act as a customer

Buffer/Buffer_Create_draft.ipynb, Buffer/Buffer_Send_text_to_Idea.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2291
=> feat: Buffer - Send text to Idea

Trello/Trello_Create_Card.ipynb, Trello/Trello_Get_Lists_on_a_Board.ipynb, Trello/Trello_List_Boards.ipynb, Trello/Trello_Update_Cards.ipynb
tell me if you want more update option
It update a target card, it can change the title, description, due and the position
=> Trello - Update Cards

Python/Python_Download_Webpage_as_PDF.ipynb
This PR resolves #2275
It contains template to download webpage as pdf
The user has to install weasyprint library. The library is already installed in Naas environment.
=> Python: Download webpage as pdf

Stripe/Stripe_List_all_customers.ipynb, Stripe/Stripe_List_all_products.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2329
=> feat: Stripe - List all products

LangChain/LangChain_Perform_QA_on_SQL_Databases.ipynb
This PR resolves #2272 
This PR adds a notebook on performing queries on an SQL database using Langchain to the awesome notebooks Langchain directory
=> feat: initializing qa on sql databases with langchain notebook

ImagineAPI.dev/ImagineAPI.dev_Create_Image.ipynb, ImagineAPI.dev/ImagineAPI.dev_Get_Image.ipynb, ImagineAPI.dev/ImagineAPI.dev_List_Images.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2337
=> feat: ImagineAPI.dev - Create Image

ImagineAPI/ImagineAPI_Create_Image.ipynb, ImagineAPI/ImagineAPI_Get_Image.ipynb, ImagineAPI/ImagineAPI_List_Images.ipynb, generate_readme.ipynb
=> feat: add linkedin logo in templates.json

Google Sheets/Google_Sheets_Delete_sheet_from_spreadsheet.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2347
=> feat: Google Sheets - Delete sheet from spreadsheet

Datetime/Datetime_Get_first_and_last_day_of_the_current_week.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2383
=> feat: Datetime - Get first and last day of the current week

Datetime/Datetime_Get_first_and_last_day_of_last_week.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2385
=> feat: Datetime - Get first and last day of last week

Datetime/Datetime_Get_the_weekday_of_the_current_date.ipynb, Datetime/Datetime_Get_weekday.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2387
=> feat: Datetime - Get weekday

Google Docs/Google_Docs_Replace_placeholders_in_document.ipynb
This PR resolves #2296
The notebook shows how to replace placeholders in a Google Docs document using the Google Docs API
=> 2296 google docs replace placeholders in document

generate_readme.ipynb
=> fix: add new image format for logo in generate_readme.ipynb

Spotify/Spotify_Get_Recently_Played_Tracks.ipynb, Spotify/Spotify_Setup_connection.ipynb
=> feat: Get recently played tracks on Spotify

Meta/Meta_Chat_with_Llama2.ipynb, OpenAI/OpenAI_Chat_with_ChatGPT3.5_turbo.ipynb, OpenAI/OpenAI_Chat_with_ChatGPT3.5_turbo_16k.ipynb, OpenAI/OpenAI_Chat_with_ChatGPT4.ipynb, spaCy/SpaCy_Build_a_sentiment_analysis_model_using_Twitter.ipynb
=> feat: update title and notebook name + fix spacy name

Spotify/Spotify_Get_Artist.ipynb
=> 2408 spotify get artist

RegEx/RegEx_Remove_emojis_from_text.ipynb, template.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2432
=> feat: RegEx - Remove emojis from text

Spotify/Spotify_Get_New_Releases.ipynb
=> 2422 spotify get new releases

Spotify/Spotify_Get_Artist_Albums.ipynb, Spotify/Spotify_Get_Artists_Top_Tracks.ipynb
=> fix(Spotify): Names for templates

LinkedIn/LinkedIn_Get_profile_top_card.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2437
=> feat: LinkedIn - Get profile top card

generate_readme.ipynb
=> fix: Update generate_readme.ipynb

LinkedIn/LinkedIn_Get_post_comments_profiles.ipynb, LinkedIn/LinkedIn_Get_post_interactions.ipynb, LinkedIn/LinkedIn_Get_post_likes_profiles.ipynb, generate_readme.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2464
=> feat: LinkedIn - Get post interactions

Naas Credits/Naas_Credits_Export_current_transaction.ipynb, Naas Credits/Naas_Credits_Export_current_transactions_to_Excel.ipynb, Naas Credits/Naas_Credits_Get_Balance.ipynb, Naas Credits/Naas_Credits_Get_current_transactions.ipynb
=> feat(Naas Credits): Add Export current transaction

Spotify/Spotify_Get_Album.ipynb, Spotify/Spotify_Get_Album_Tracks.ipynb, Spotify/Spotify_Get_Artist.ipynb, Spotify/Spotify_Get_Artist_Albums.ipynb, Spotify/Spotify_Get_Artist_Related_Artists.ipynb, Spotify/Spotify_Get_Artists_Top_Tracks.ipynb, Spotify/Spotify_Get_New_Releases.ipynb, Spotify/Spotify_Get_Playlist_Items.ipynb, Spotify/Spotify_Get_Recently_Played_Tracks.ipynb, Spotify/Spotify_Search_for_Item.ipynb
Resolves #2472 and replaced all the Spotify author links with the correct link.
=> 2472 spotify get playlist items

Spotify/Spotify_Get_Users_Playlists.ipynb
=> feat(Spotify): Get Users Playlists

Pipedrive/Pipedrive_Get_a_note.ipynb, Pipedrive/Pipedrive_Get_all_notes.ipynb, Pipedrive/Pipedrive_Update_a_deal.ipynb, Pipedrive/Pipedrive_Update_a_note.ipynb
=> feat: add notes templates

Matplotlib/Matplotlib_Create_word_cloud.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2502
=> feat: Matplotlib - Create word cloud

Naas API/Naas_API_Create_Workspace.ipynb, Naas API/Naas_API_Delete_Workspace.ipynb, Naas API/Naas_API_List_Registries.ipynb, Naas API/Naas_API_List_Workspace_Users.ipynb, Naas API/Naas_API_List_Workspaces.ipynb, Naas API/Naas_API_List_workspaces.ipynb, Naas API/Naas_API_Update_Workspace.ipynb, Naas API/Naas_API_Update_Workspace_Users.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2510
=> feat: Naas API - List workspaces

Pipedrive/Pipedrive_Add_an_activity.ipynb
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2512
=> feat: Pipedrive - Add an activity

LangChain/LangChain_Create_Agent.ipynb, LangChain/LangChain_Use_GraphCypherQAChain_Neo4j.ipynb
This PR resolves #2515 
(Provide a description of what this PR does and why it's needed.)
=> feat: add langchain create agent + use graphcypherqachain

LinkedIn/LinkedIn_Rank_Direct_Conversations_by_Messages_Count.ipynb
=> feat: add template

GitHub/GitHub_Get_an_organization.ipynb, GitHub/GitHub_Get_profile_from_user.ipynb, Hunter.io/Hunter.io_Find_email.ipynb, Hunter.io/Hunter.io_Search_domain.ipynb, Hunter.io/Hunter.io_Verify_email.ipynb
This PR resolves #2546, 2547, 2548
Hunter.io discoveries to cover another potential platform for a template.
=> 2527 GitHub and hunter.io

Instagram/Instagram_Extract_details_from_account.ipynb
=> 2559 instagram extract details from account

Instagram/Instagram_Get_comments_from_post.ipynb, Twitter/Twitter_Get_tweets_by_username.ipynb
=> feat: twitter get recent tweets

.github/PULL_REQUEST_TEMPLATE.md, SendGrid/SendGrid_Add_or_Update_Contacts.ipynb, SendGrid/SendGrid_Get_Contacts.ipynb, SendGrid/SendGrid_Get_Lists.ipynb, SendGrid/SendGrid_Get_Single_Sends.ipynb, SendGrid/SendGrid_Get_Unsubscribes.ipynb
=> feat: add notebooks sendgrid
