jupyter-naas/awesome-notebooks

Notion/Notion_Push_data_from_Gsheets.ipynb

Hi !
I add the engine gsheets data to notion database,
In the notebook, you have to put your gsheet spreadsheet_id, the name of the sheet, your notion token and the database ID.
After that, you have to put your unique variable to compare the two set of data.
And for the finish, you have to fill the two functions `write_in_notion` and `update_page_in_notion`
**Exemple,** `response[1]` is the date, you ahve to write in the two function `page.date("Date", response[1])`
I stay available for all questions for the use of the notebook, thank you in advance for your feedback!

feat: add the engine gsheets data to notion database

---

Sendinblue/Sendinblue_Get_no_of_emails_sent.ipynb

Added the template for getting the number of emails sent through a Sendinblue campaign.
A couple of notes,
- This is for getting the number of emails sent through a specified campaign. If the idea is to get a report of the emails sent through all campaigns, let me know and I will update accordingly.
- I have used the attribute 'sent' to get the number of emails sent. There is another attribute 'delivered', however, I feel that 'sent' is the correct option?
Here is a link to the API documentation,
https://developers.sendinblue.com/reference/getemailcampaigns-1

Sendinblue - Get number of emails sent

---

Dash/Dash_Plotly_Dynamic_Link.ipynb

Input:
✔️ App setup
Model:
✔️ Create plotly graph
✔️ Create a Dash app with Plotly graph
✔️ Setup callback
Output:
✔️ Display app
This PR closes #1249

Added dynamic link on label click plotly chart python

---

.github/workflows/create_link_to_template.yaml

The **create_link_to_template.yaml** file creates a comment in PR with a link to the template (the .ipynb file that was either modified or added).

added create template link yaml file

---

LinkedIn/LinkedIn_Send_like_to_post.ipynb

This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2103

feat: LinkedIn - Send like to post

---

Advertools/Advertools_Check_website_pages_status_code.ipynb

This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2099

feat: Advertools - Check website pages status code

---

Python/Python_Get_emojis_from_text.ipynb

This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2166

feat: Python - Get emojis from text

---

CONTRIBUTING.md
README_template.md

feat: create CONTRIBUTING.md

---

.github/workflows/generate_certificate.yaml

This PR resolves #2264 
Fix the certificate template name issue which replaces the `actor` with the `author` of the PR in the certificate workflow.

Fix the certificate name generated on PR merge

---

Matplotlib/Matplotlib_Create_Piechart.ipynb

closes : #2255 
It shows how to use matplotlib piecharts

2255 matplotlib create piechart

---

Appwrite/Appwrite_User_Authentication.ipynb

closes : #2270 
(Provide a description of what this PR does and why it's needed.) It shows how to add , delete and list users using app write 
@FlorentLvr  I've created new project and Api secret key for testing as provided key isn't working . I'll delete it as soon as it's merged you can check if it's working directly for now .

2270 appwrite user authentication

---

Trello/Trello_Delete_Cards.ipynb

sounds good, let me know what you think ;)
It delete a target card using API

feat: Trello - Delete cards

---

Worldometer/Worldometer_World_population_evolution_and_projections.ipynb

Worldometer has removed "UrbanPop" "UrbanPop %" from the table, hence the table was breaking as it does a check if all columns are the same as TABLE_COLS.
This PR resolves #2177
Fixes the ongoing bug with the Worldometer_World_population_evolution_and_projections.ipynb file

fix: removed unused table cols and added column preprocessor func

---

Matplotlib/Matplotlib_Plot_Wireframe.ipynb

This PR resolves #2278
This PR contains a notebook which explains on how to create a 3d Wireframe plot using matplotlib

feat: plot wireframe using matplotlib

---

.gitignore
Python/Python_Convert_audiofile_from_wav_to_mp3.ipynb

This PR resolves #2310
Added a function to identify the new ffmpeg binary and move it accordingly. Also updated the example wav file as the older one was not found.

fix: Added generic ffmpeg package helper and updated sample wav file

---

Google Drive/Google_Drive_Create_shareable_public_link.ipynb

This PR resolves #2295
This notebook will show how to create a shareable public link from a file stored in Google Drive

2295 google drive create shareable public link

---

Google Sheets/Google_Sheets_List_sheets_from_spreadsheet.ipynb

This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2345

feat: Google Sheets - List sheets from spreadsheet

---

Hugging Face/Hugging_Face_Token_Classification_for_Sequence_Labelling_Tasks_using_Inference_API.ipynb

This PR resolves #2366
This notebook demonstrates how to utilize the [inference endpoints](https://huggingface.co/docs/inference-endpoints/index) (additional information can be found here: [link](https://huggingface.co/docs/api-inference/index#-hosted-inference-api)) of hugging face models for token classification based sequence labelling tasks.
Provide supporting docs, limitations if any, video of the template, or anything that you want to share to support your PR - N/A

Hugging Face - Token Classification for Sequence Labelling Tasks using Inference API

---

Pyvis/Pyvis_Create_a_network_visualization.ipynb
Pyvis/Pyvis_Visualize_awesome_notebooks_network.ipynb

This PR resolves #2390
(One iteration of the network visualization with data extracted from templates.json file.
Notes:
- Edges are undirected in this first version.
- The so-called "physics" for the mechanic model is set to force_atlas_2based. I think is the best suited gravity modelation for this network otherwise barnes_Hut is also a good option (the one used in the GOT example), but a bit messy perhaps.
- I found mostly Tool <-> Template edges
- Few (but some) situations of the kind Tool <-> Template <-> Tool
- A bit unbalanced node dimensions. For instance, OpenAi is huge compared to the rest and I had to fix it in a corner of the canvas due to gravity issues.
- I fixed Naas node in the center of the canvas, that is, [x = 0, y = 0]
- I realized some nodes may have the wrong image …

feat: creating Pyvis network graph

---

Spotify/Spotify_Get_User_Top_Items.ipynb

feat(Spotify): Get user top items

---

Spotify/Spotify_Remove_Playlist_Items.ipynb

Resolves #2470 
Before: 
After:

2470 spotify remove playlist items

---

Stripe/Stripe_Create_a_payment_link.ipynb

This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/2492

feat: Stripe - Create a payment link

---

Python/Python_CountLettersWordsPhrases.ipynb
Python/Python_Count_characters_from_text.ipynb
Python/Python_Extract_Hashtags.ipynb

This PR resolves #2519 
Extracts hashtags from a sentence as well as counts the appearance of letters, words and phrases.

feat: case studies

---

TikTok/TikTok_Get_liked_videos.ipynb
TikTok/TikTok_Get_liked_videos_transcripts.ipynb

This PR is resultant from DM conversation with @jravenel about new TikTok notebooks
Provides notebooks for gathering a list of liked TikTok videos of a given user, and a notebook which returns that list along with transcriptions of the videos.

feat: tiktok get liked videos

---

Hunter.io/Hunter.io_Find_email.ipynb

fix: hunter.io find email
